version: '3'
services:
  nginx1: 
    image: 'myservice/nginx:v1'
    healthcheck:
      test: ["CMD", "cat", "/var/run/nginx.pid"]
      interval: 30s
      timeout: 15s
      retries: 105
    ports:
    - 80:80
    restart: always
    volumes:
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf   
    depends_on:
    - springboot1
    - springboot2
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    tty: true
    networks:
    - webnet    

  springboot1:
    image: 'myservice/springboot:v2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://locahost:8080/checkHealth"]
      interval: 30s
      timeout: 15s
      retries: 10
    ports:
    - 5001:8080
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    networks:
    - webnet     

  springboot2:
    image: 'myservice/springboot:v2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/checkHealth"]
      interval: 30s
      timeout: 15s
      retries: 10
    ports:
    - 5002:8080
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    networks:
    - webnet
networks:
  webnet:
