version: '3'
services:
  nginx1: 
    image: 'myservice/nginx:1.0'
    ports:
    - 80:80
    restart: always
    volumes:
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf   
    depends_on:
    - springboot1
    - springboot2
    tty: true

  springboot1:
    image: 'myservice/springboot:1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://locahost:8080/checkHealth"]
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
    - 5001:8080
      
  springboot2:
    image: 'myservice/springboot:1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/checkHealth"]
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
    - 5002:8080

